name: Drift Check

on:
  push:
    paths:
      - 'sample_data.csv'
      - '.github/workflows/drift-check.yml'
  workflow_dispatch:

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run drift check
        run: |
          python drift_check.py --csv sample_data.csv --column age_int --expected_mean 30 --threshold 0.0
