name: Install Dependencies

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'sample_data.csv'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'sample_data.csv'
      - 'README.md'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
