# .github/workflows/python-ci.yml
# GitHub Actions workflow for Python 3.10 project

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]  # Specify the Python versions to test against
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pydocstyle
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle .
    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -v
